import random
import math

# enter the lower and upper bound 
lowerbound = int(input("Enter the lowerbound:- "))
upperbound = int(input("Enter the Upperbound:- "))

# random number generated by compiler
x = random.randint(lowerbound, upperbound)

# print the calculated guess number
print("\n \t You've only", round(math.log(upperbound-lowerbound+1, 2)), "chance to guess the Integer! \n")

# Initializing count 
count = 0

#formula of minimum number of guessing 
formula = math.log(upperbound-lowerbound+1, 2)

# for calculation of minimum number of guess depends upon range
while count < formula:
    count +=1

    # take guess number
    guess = int(input("Guess the number: -"))

    #testing codition
    if x == guess:
        print("Congratulation, you did it in ", count, "try")
        break
    elif x > guess:
        print("You guessed too small!!!")
    elif x < guess:
        print("You guessed too high!!!")
        
#if guessing is more than required guess than
if count >= formula:
    print("\n The number is: ", x)
    print("Better luck, Next time!")
